### ISSUE TITLE
Feature - Login

### ISSUE THREAD

**Issue by pepibumur** [SugarTeam/SoundCloudSwift#1]
## TODO :white_check_mark: 
- [ ] Implement SoundCloudSession (struct)
- [ ] Implement Oauth Flow
  - [ ] Using a SafariController
  - [ ] Using a WebView
- [ ] Implement SessionStorage controller
