### ISSUE TITLE
Feature - Entity protocol

### ISSUE THREAD

**Issue by pepibumur** [SugarTeam/SoundCloudSwift#4]
### TODO :white_check_mark: 
- [ ] Define mapper related methods
- [ ] Define *ModelPredicate* `David.likes().by(.Tags(["ya ves", "joder"]), .Query("acdc"))`
- [ ] Implement an example entity
